// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: enum.proto

package validator_examples

import fmt "fmt"
import github_com_simplesurance_go_proto_validators "github.com/simplesurance/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SomeMsg) Validate() error {
	if _, ok := Action_name[int32(this.Do)]; !ok {
		return github_com_simplesurance_go_proto_validators.FieldError("Do", fmt.Errorf(`value '%v' must be a valid Action field`, this.Do))
	}
	return nil
}
